table <- read.table("household_power_consumption.txt",header = TRUE,sep = ";")
table2007 <- subset(table,table$Date == "1/2/2007"|table$Date == "2/2/2007")
datetime <- strptime(paste(table2007$Date,table2007$Time),format = "%d/%m/%Y %H:%M:%S")
table2007 <- cbind(datetime,table2007)
table2007$Global_active_power <- as.numeric(table2007$Global_active_power)
png("plot3.png",width = 480, height = 480, units = "px")
par(mfrow=c(1,1),mar=c(2,5,2,2))
with(table2007,plot(datetime,Sub_metering_1,type = "l",ylab = "Energy sub metering"))
lines(table2007$datetime,table2007$Sub_metering_2,type = "l",col ="red")
lines(table2007$datetime,table2007$Sub_metering_3,type = "l",col ="blue")
legend("topright",col= c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),bty="o",lty = 1)
dev.off()